POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username":"dfast",
    "password":"dfast17"
}
###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username":"dfast17",
    "password":"dfast17"
}
###
POST http://localhost:3001/user/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmYXN0IiwiaWF0IjoxNzEyMTMyNTkxLCJleHAiOjE3MTI1NjQ1OTF9.OwVMDKkfRMd7gyyzlTqV5NuWMwwjsuCn0q88YLUDDfM

{
    "value":"d"
}
###
POST http://localhost:3001/user/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmYXN0MTciLCJpYXQiOjE3MTIxMzI3MzEsImV4cCI6MTcxMjU2NDczMX0._GMM5OMQwuyVOEhCKL6_1DIEIu9OcT6QIEzx5wQbwFA

{
    "value":"d"
}
###
GET http://localhost:3001/user/search/key/D

